name: ${project.artifactId}
version: ${project.version}
author: OhBlihv
main: net.auscraft.BlivUtils.BlivUtils
description: 'A collection of Utilities, which may be completely useless.'
softdepend: [Vault, PermissionsEx]
commands:
  bu:
    description: 'Base BlivUtils command, including version and reload commands'
  say:
    description: 'Overrides /say to look decent.'
    usage: 'Usage: /<command> <string>'
  purch:
    description: 'A printout of the recent purchase on the AusCraft Store. (CONSOLE)'
    usage: 'Usage: /<command> <string>'
  lore:
    description: 'Edit/Remove the lore and name of a held item'
    usage: 'Usage: /<command> <string>'
  fixClaim:
    description: 'Adds a once a restart item fix'
  xpClaim:
    description: 'Adds a once a restart xp claim'
  enderperm:
    description: 'Adds the individual perms for upgrading Ender rank'
    usage: 'Usage: /<command> <add|remove> <player> <package>'
  enderrank:
    description: 'Adds a package to a players account on purchase of the Ender Rank (CONSOLE)'
    usage: 'Usage: /<command> <player> <package>'
  health:
    description: 'A toggle between the default max health and the Ender rank max health'
  wstop:
    description: 'Adds a delay to the /stop command. (Console Only!)'
    usage: 'Usage in Console: /<command>'
  sudo:
    description: 'Does that thing that stops sinny from abusing.'
    usage: 'Usage: /<command> <string>'
  rank:
    description: 'Shows simple help for a rank, with links to the wiki for more.'
    usage: 'Usage: /<command> <rank>'
    aliases: [ranks]
  buyrank:
    description: 'Opens the rank purchasing menu, and allows the user to purchase a rank they choose'
  promoadmin:
    description: 'Promotes an existing player to Admin for 30 days'
    usage: 'Usage: /<command> <player> <amount> [day(s) OR month(s)]'
  updateadmin:
    description: 'Adds or removes time from an Admins rank'
    usage: 'Usage: /<command> <player> <amount> <day(s) OR month(s)>'
  updatetime:
    description: 'Adds or removes time from a players rank (defined in command)'
    usage: 'Usage: /<command> <player> <rank> <amount> <day(s) OR month(s)>'
  promoteme:
    description: 'Confirms the purchase of a rank using /buyrank'
  timeleft:
    description: 'Checks the players time left of a rank'
  prefix:
    description: 'Change your own prefix'
  chat:
    description: 'Access to the chat colour changing utility'
  colourme:
    description: 'Confirmation command for the /chat menu'
  credits:
    description: 'Utility and balance displays for Credits'
    usage: 'Usage: /<command> [arg]'
  servers:
    description: 'Provides information on the available servers'
    usage: 'Usage: /<command> [args]'
  present:
    description: 'A bit of Christmas fun!'
  voteprint:
    description: 'Prints out a vote message, nicely formatted and translated'
    usage: 'Usage: /<command> <name> <reward> <service>'
  voteparty:
    description: 'Starts a vote party, where bonus rewards are more likely to drop'
    usage: 'Usage: /<command> [chance]'
  timedadd:
    description: 'Adds a command to a player for a defined amount of time'
    usage: 'Usage: /<command> <player> <time> <second[s]/minute[s]/hour[s]/day[s]> <command>'
  onick:
    description: 'One-time Nickname change (no colour) on first join'
    usage: 'Usage: /<command> <nick>'
permissions:
  blivutils.*:
    description: Access every useless utility!
    default: op
    children:
      blivutils.say: true
      blivutils.sudo: true
      blivutils.promote.magmaslime: true
      blivutils.promote.blaze: true
      blivutils.promote.pigzombie: true
      blivutils.promote.ghast: true
      blivutils.promote.admin: true
      blivutils.promote.admin.check: true
      blivutils.promote.admin.update: true
      blivutils.chat.use: true
      blivutils.prefix: true
      blivutils.credits.admin: true