name: ${project.artifactId}
version: ${project.version}
author: OhBlihv
main: net.auscraft.BlivUtils.BlivUtils
description: 'A collection of Utilities, which may be completely useless.'
softdepend: [Vault, PermissionsEx]
commands:
  bu:
    description: 'Base BlivUtils command, including version and reload commands'
  say:
    description: 'Overrides /say to look decent.'
    usage: 'Usage: /<command> <string>'
  wstop:
    description: 'Adds a delay to the /stop command. (Console Only!)'
    usage: 'Usage in Console: /<command>'
  sudo:
    description: 'Does that thing that stops sinny from abusing.'
    usage: 'Usage: /<command> <string>'
  rank:
    description: 'Shows simple help for a rank, with links to the wiki for more.'
    usage: 'Usage: /<command> <rank>'
    aliases: [ranks]
  buyrank:
    description: 'Opens the rank purchasing menu, and allows the user to purchase a rank they choose'
  promoadmin:
    description: 'Promotes an existing player to Admin for 30 days'
    usage: 'Usage: /<command> <player> <amount> [day(s) OR month(s)]'
  updateadmin:
    description: 'Adds or removes time from an Admins rank'
    usage: 'Usage: /<command> <player> <amount> [day(s) OR month(s)]'
  promoteme:
    description: 'Confirms the purchase of a rank using /buyrank'
  timeleft:
    description: 'Checks the players time left of a rank'
  prefix:
    description: 'Change your own prefix'
  chat:
    description: 'Access to the chat colour changing utility'
  colourme:
    description: 'Confirmation command for the /chat menu'
permissions:
  blivutils.*:
    description: Access every useless utility!
    default: op
    children:
      blivutils.say: true
      blivutils.sudo: true
      blivutils.promote.magmaslime: true
      blivutils.promote.blaze: true
      blivutils.promote.pigzombie: true
      blivutils.promote.ghast: true
      blivutils.promote.admin: true
      blivutils.promote.admin.check: true
      blivutils.promote.admin.update: true
      blivutils.chat.use: true
      blivutils.prefix: true