#---------------------------------------
#			BlivUtils Config
#---------------------------------------

#Below are examples and help on how to use the config.

#scheduler:
        
        #enabled: 1
            #Is this server a server which should be counting the rank times?
            #(Only enable this on a main server if on a proxy)
            
        #unit: hours
            #Which unit to count by?
            #Valid Options: seconds, minutes, hours (Case-Sensitive)
            
        #time: 1
            #Time to check whether ranks have run out in minutes (Default 60 Minutes)
        
    #save:
        #time: 5
            #Time to save the world.
            
        #unit: minutes
            #Which unit to count by?
            #Valid Options: seconds, minutes, hours (Case-Sensitive)
        
    #mysql:
        #Database options for the Credit system
        #Setup variable related to setting up the database.
        #setup: 0
            #0 = First run. Does not create a table, since the config is just created
            #1 = Second run. Creates table in the given database (database must exist prior to starting)
            #2 = Subsequent runs. Table is created, and BlivUtils will not try to recreate it.
            #If problems, set it to 0 (Default)
            
        # user: minecraft
        # pass: minecraft
        # url: jdbc:mysql://localhost:3306/minecraft
            #Examples:
            #user = "username"
            #pass = "password"
            #url = "jdbc:mysql://localhost:3306/minecraftdb"
        
#------------------------------------------------------------------------------------
options:
    toggle:
        rankpromotion: 0
        credits: 0
        presents: 0
    scheduler:
        enabled: 1
        unit: hours
        time: 1
    save:
        time: 5
        unit: minutes
    rewards:
        #Move me later
        # <NAME>,<ENCHANTNAME:LEVEL:VARIANCE [ ENCHANTNAME:LEVEL:VARIANCE...]>,<ITEM ID>,<LORE>
        # <NAME> -- Can include spaces and any other character but ','
        # <ENCHANTNAME:LEVEL:VARIANCE> - List of enchantments coming soon, Base level, Number of levels different from the base the enchant level can be.
        # <ITEM ID> - ID of the reward
        # <LORE> - Lore to display on the item
        pool1: {}
        pool2: {}
        pool3: {}
        pool4: {}
        pool5: {}
    mysql:
        setup: '0'
        user: minecraft
        pass: minecraft
        url: jdbc:mysql://localhost:3306/minecraft